---

galaxy_info:
  author: your_name
  description: Example role
  company: your_company
  license: license (e.g. MIT)
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal